### ISSUE TITLE
Объединяет инфо ячейки после загрузки данных

### ISSUE THREAD

**Issue by AliaksandrHudnyi** [AlexandrPavlovski/gym-statistics#1]
Ячейки удалены
Мышцы | Отдых | Подходы | Работа | План | MaxLast | Дата | Чувство | Режим | Зал
https://i.imgur.com/0CPwqZA.png

**Comment by AlexandrPavlovski** [comment]
Исправлено в версии 1.1
#6

**Comment by AliaksandrHudnyi** [comment]
Tested. Fixed.
