### ISSUE TITLE
Программа не учитывает занятие если тренеровался не в пн,ср,пт

### ISSUE THREAD

**Issue by AliaksandrHudnyi** [AlexandrPavlovski/gym-statistics#3]
Пример:
Тренеровку "Мышцы Спины Combo#3" за среду сделали во вторник
Программа должна предложить на след среду "Мышцы Спины Combo#4", а предлагает опять "Мышцы Спины Combo#3"

**Comment by AlexandrPavlovski** [comment]
Исправлено в версии 1.1
#6

**Comment by AliaksandrHudnyi** [comment]
Tested. Fixed
