### ISSUE TITLE
Дата введёная вручную имеет в начале своей записи '

### ISSUE THREAD

**Issue by AliaksandrHudnyi** [AlexandrPavlovski/gym-statistics#4]
Дата не отображается как дата Пример: https://i.imgur.com/UjgUrzn.png
Как должно быть: https://i.imgur.com/eZp4Y95.png

**Comment by AlexandrPavlovski** [comment]
Исправлено в версии 1.1
#6

**Comment by AliaksandrHudnyi** [comment]
Tested. Fixed.
