### ISSUE TITLE
Пожалуйста добавь поля Режим для редактирования

### ISSUE THREAD

**Issue by AliaksandrHudnyi** [AlexandrPavlovski/gym-statistics#5]

**Comment by AlexandrPavlovski** [comment]
Поля "Режим" и "Зал" в версии 1.1 (#6) заполняются значениями предыдущего занятия. Добавлять их в программу для редактирования будет непрактично потому что они займут много места, а редактируются они очень редко.

**Comment by AliaksandrHudnyi** [comment]
Tested. Fixed.
